graph TD
  print.tbl["print.tbl()"] --> format.tbl["format.tbl()"]
  format.tbl --> tbl_format_setup["tbl_format_setup()"]
  options(Options: n and n_extra) -.-> tbl_format_setup
  format.tbl --> tbl_format_header["tbl_format_header()"]
  format.tbl --> tbl_format_body["tbl_format_body()"]
  format.tbl --> tbl_format_footer["tbl_format_footer()"]
  tbl_format_setup -.-> tbl_sum["tbl_sum()"]
  tbl_sum -.-> setup(Setup object)
  tbl_format_setup -.-> ctl_new_compound_pillar["ctl_new_compound_pillar()"]
  ctl_new_compound_pillar -.-> ctl_new_pillar["ctl_new_pillar()"]
  ctl_new_pillar -.-> setup(Setup object)
  setup -.-> tbl_format_header
  setup -.-> tbl_format_body
  setup -.-> tbl_format_footer
  tbl_format_header -.-> print(Printed output)
  tbl_format_body -.-> print
  tbl_format_footer -.-> print
