---
title: "Controlling display of numbers"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{Controlling display of numbers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Tibbles print numbers with three significant digits by default, switching to scientific notation if the available space is too small.
Underlines are used to highlight groups of three digits.
This display works for many, but not for all use cases.

```{r include = FALSE}
pkgload::load_all()
```

```{r}
library(pillar)
```

## The `num()` constructor

```{r}
#' @export
num <- function(x, sigfig = NULL, digits = NULL, 
                label = NULL, scale = NULL, display = NULL) {
  
  stopifnot(is.numeric(x))
  vctrs::new_vctr(
    x,
    sigfig = sigfig,
    digits = digits,
    label = label,
    scale = scale,
    display = display,
    class = "tibble_num",
    inherit_base_type = TRUE
  )
}

#' @importFrom pillar pillar_shaft
#' @export
pillar_shaft.tibble_num <- function(x, ...) {
  data <- vctrs::vec_data(x)
  scale <- attr(x, "scale")
  if (!is.null(scale)) {
    data <- data * scale
  }
  
  pillar_shaft(
    data,
    sigfig = attr(x, "sigfig"),
    digits = attr(x, "digits"),
    display = attr(x, "display")
  )
}

#' @export
type_sum.tibble_num <- function(x, ...) {
  label <- attr(x, "label")
  
  if (!is.null(label)) {
    I(label)
  } else {
    display <- attr(x, "display")
    if (is.null(display)) {
      display <- "num"
    }
    
    sigfig <- attr(x, "sigfig")
    digits <- attr(x, "digits")
    
    if (is.null(digits)) {
      if (is.null(sigfig)) {
        display
      } else {
        paste0(display, ":", sigfig)
      }
    } else {
      paste0(display, ":.", digits)
    }
  }
}
```

## Using `num()`

```{r}
library(tibble)
```


### Significant figures

```{r}
tibble(
  x3 = num(9:11 * 100 + 0.5, 3),
  x4 = num(9:11 * 100 + 0.5, 4),
  x5 = num(9:11 * 100 + 0.5, 5),
)
```


### Decimal digits

```{r}
tibble(
  x0 = num(9:11 * 100 + 0.5, digits = 0),
  x1 = num(9:11 * 100 + 0.5, digits = 1),
  x2 = num(9:11 * 100 + 0.5, digits = 2),
)
```


### Currency

```{r}
tibble(
  usd = num(9:11 * 100 + 0.5, digits = 2, label = "USD"),
  gbp = num(9:11 * 100 + 0.5, digits = 2, label = "£"),
  chf = num(9:11 * 100 + 0.5, digits = 2, label = "SFr")
)
```


### Percentage

```{r}
tibble(
  small  = num(9:11 / 1000 + 0.00005, label = "%", scale = 100),
  medium = num(9:11 /  100 + 0.0005 , label = "%", scale = 100),
  large  = num(9:11 /   10 + 0.005  , label = "%", scale = 100)
)
```


### Notation

```{r}
tibble(
  sci  = num(10^(-13:6), display = "sci"),
  eng  = num(10^(-13:6), display = "eng"),
  dec  = num(10^(-13:6), display = "dec")
)
```
