test_that("same pillar at different widths", {
  v <- 10^c(-9, -6, 3, 9)
  x <- pillar(v)
  expect_equal(get_min_width(x$shaft), 7)
  expect_equal(get_width(x$shaft), 7)
  expect_snapshot(pillar(v, width = 4))
  expect_snapshot(pillar(v, width = 7))
  expect_snapshot(pillar(v, width = 10))
  expect_snapshot(pillar(v, width = 15))
  expect_snapshot(pillar(v, width = 22))
})
