context("format_multi")

test_that("output test", {
  x <- list(1:3 + 0.23, letters[1:3], factor(letters[1:3]), ordered(letters[1:3]))
  expect_colformat_output(xf = multicolformat(x, width = 4), filename = "multi-04.txt")
  expect_colformat_output(xf = multicolformat(x, width = 5), filename = "multi-05.txt")
  expect_colformat_output(xf = multicolformat(x, width = 6), filename = "multi-06.txt")
  expect_colformat_output(xf = multicolformat(x, width = 7), filename = "multi-07.txt")
  expect_colformat_output(xf = multicolformat(x, width = 8), filename = "multi-08.txt")
  expect_colformat_output(xf = multicolformat(x, width = 9), filename = "multi-09.txt")
  expect_colformat_output(xf = multicolformat(x, width = 10), filename = "multi-10.txt")
  expect_colformat_output(xf = multicolformat(x, width = 11), filename = "multi-11.txt")
  expect_colformat_output(xf = multicolformat(x, width = 12), filename = "multi-12.txt")
  expect_colformat_output(xf = multicolformat(x, width = 13), filename = "multi-13.txt")
  expect_colformat_output(xf = multicolformat(x, width = 14), filename = "multi-14.txt")
  expect_colformat_output(xf = multicolformat(x, width = 15), filename = "multi-15.txt")
  expect_colformat_output(xf = multicolformat(x, width = 16), filename = "multi-16.txt")
  expect_colformat_output(xf = multicolformat(x, width = 17), filename = "multi-17.txt")
  expect_colformat_output(xf = multicolformat(x, width = 18), filename = "multi-18.txt")
  expect_colformat_output(xf = multicolformat(x, width = 19), filename = "multi-19.txt")
  expect_colformat_output(xf = multicolformat(x, width = 20), filename = "multi-20.txt")
  expect_colformat_output(xf = multicolformat(x, width = 21), filename = "multi-21.txt")
  expect_colformat_output(xf = multicolformat(x, width = 22), filename = "multi-22.txt")
  expect_colformat_output(xf = multicolformat(x, width = 23), filename = "multi-23.txt")
  expect_colformat_output(xf = multicolformat(x, width = 24), filename = "multi-24.txt")
  expect_colformat_output(xf = multicolformat(x, width = 25), filename = "multi-25.txt")
  expect_colformat_output(xf = multicolformat(x, width = 26), filename = "multi-26.txt")
  expect_colformat_output(xf = multicolformat(x, width = 27), filename = "multi-27.txt")
  expect_colformat_output(xf = multicolformat(x, width = 28), filename = "multi-28.txt")
  expect_colformat_output(xf = multicolformat(x, width = 29), filename = "multi-29.txt")
})
